### ISSUE TITLE
Re-implement the fibonacci algorithm.

### ISSUE THREAD

**Issue by koluacik** [koluacik/fibonacci-Hacktoberfest#1]
Appearently, each fibonacci call makes two new fibonacci calls which is a terribly inefficient type of recursion. Find a better recursive solution (iterative is fine). 
Note: i mark spam PR's as spam.

**Comment by yemikifouly** [comment]
I will take this.

**Comment by Eshan2203** [comment]
Can i take this ?

**Comment by Eshan2203** [comment]
#6 can you chek this ?

**Comment by koluacik** [comment]
Hello, since this is not a real project and more of a training oriented repo, I decided to keep the original code intact and accept contributions in seperate files. If your solution solves the problem above, please submit a PR. Thanks for your contributions and happy hacking :)
